# Generated by Django 5.1.4 on 2025-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanscenario',
            name='annual_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanscenario',
            name='monthly_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanscenario',
            name='total_interest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanscenario',
            name='total_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
